version: '3.8'

services: 
  postgres:
    image: postgres
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: leetcode-web
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env.prod

  submission-webhook:
    build:
      context: .
      dockerfile: apps/submission-webhook/Dockerfile
    container_name: leetcode-submission-webhook
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres

volumes:
  postgres_data:

