services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5440:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: codequest-web
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  submission-webhook:
    build:
      context: .
      dockerfile: apps/submission-webhook/Dockerfile
    container_name: codequest-submission-webhook
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
