services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: codequest-web
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - NEXTAUTH_SECRET=your-secret-key-change-in-production
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_JUDGE0_SERVER=${NEXT_PUBLIC_JUDGE0_SERVER:-https://judge0-ce.p.rapidapi.com}
      - JUDGE0_CALLBACK_URL=http://submission-webhook:8080/submission-callback

  submission-webhook:
    build:
      context: .
      dockerfile: apps/submission-webhook/Dockerfile
    container_name: codequest-submission-webhook
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres

volumes:
  postgres_data:
